version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=msd_catalog
      - POSTGRES_DB=msd_catalog

  web:
    build: .
    command: "python manage.py runserver 127.0.0.1:8000"
    environment:
      - ENVIRONMENT=local
    env_file:
      - .env
    volumes:
      - .:/fuzzy
    ports:
      - 8000:8000
    depends_on:
      - db
      - elastic
    links:
      - db
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - "9200"
      - "9300"
