version: '3'

services:
  db:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=fuzzy
      - POSTGRES_DB=fuzzy
      - POSTGRES_PASSWORD=fuzzy

  web:
    build: .
    command: "python manage.py runserver"
    environment:
      - ENVIRONMENT=local
    env_file:
      - .env
    volumes:
      - .:/fuzzy
    ports:
      - 8000:8000
    depends_on:
      - db
      - elastic
    links:
      - db
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - "9200"
      - "9300"
